CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    user_password TEXT NOT NULL,
    user_email TEXT NOT NULL
);

INSERT INTO public.users (user_name,user_password,user_email) VALUES ('admin','123','admin@gmail.com');

CREATE TABLE habits (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    name varchar NOT NULL,
    times_completed INTEGER DEFAULT 0 NOT NULL,
    notes varchar NOT NULL
);

